# Generated by Django 2.2.3 on 2019-07-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('Modify_time', models.DateTimeField(auto_now=True)),
                ('phoneNumber', models.CharField(max_length=11, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
